<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            "AF" => ["id" => "1", "name" => "Afghanistan", "iso3" => "AFG", "currency_code" => "AFN"],
            "AX" => ["id" => "2", "name" => "Aland Islands", "iso3" => "ALA", "currency_code" => "EUR"],
            "AL" => ["id" => "3", "name" => "Albania", "iso3" => "ALB", "currency_code" => "ALL"],
            "DZ" => ["id" => "4", "name" => "Algeria", "iso3" => "DZA", "currency_code" => "DZD"],
            "AS" => ["id" => "5", "name" => "American Samoa", "iso3" => "ASM", "currency_code" => "USD"],
            "AD" => ["id" => "6", "name" => "Andorra", "iso3" => "AND", "currency_code" => "EUR"],
            "AO" => ["id" => "7", "name" => "Angola", "iso3" => "AGO", "currency_code" => "AOA"],
            "AI" => ["id" => "8", "name" => "Anguilla", "iso3" => "AIA", "currency_code" => "XCD"],
            "AQ" => ["id" => "9", "name" => "Antarctica", "iso3" => "ATA", "currency_code" => "AAD"],
            "AG" => ["id" => "10", "name" => "Antigua and Barbuda", "iso3" => "ATG", "currency_code" => "XCD"],
            "AR" => ["id" => "11", "name" => "Argentina", "iso3" => "ARG", "currency_code" => "ARS"],
            "AM" => ["id" => "12", "name" => "Armenia", "iso3" => "ARM", "currency_code" => "AMD"],
            "AW" => ["id" => "13", "name" => "Aruba", "iso3" => "ABW", "currency_code" => "AWG"],
            "AU" => ["id" => "14", "name" => "Australia", "iso3" => "AUS", "currency_code" => "AUD"],
            "AT" => ["id" => "15", "name" => "Austria", "iso3" => "AUT", "currency_code" => "EUR"],
            "AZ" => ["id" => "16", "name" => "Azerbaijan", "iso3" => "AZE", "currency_code" => "AZN"],
            "BS" => ["id" => "17", "name" => "Bahamas", "iso3" => "BHS", "currency_code" => "BSD"],
            "BH" => ["id" => "18", "name" => "Bahrain", "iso3" => "BHR", "currency_code" => "BHD"],
            "BD" => ["id" => "19", "name" => "Bangladesh", "iso3" => "BGD", "currency_code" => "BDT"],
            "BB" => ["id" => "20", "name" => "Barbados", "iso3" => "BRB", "currency_code" => "BBD"],
            "BY" => ["id" => "21", "name" => "Belarus", "iso3" => "BLR", "currency_code" => "BYN"],
            "BE" => ["id" => "22", "name" => "Belgium", "iso3" => "BEL", "currency_code" => "EUR"],
            "BZ" => ["id" => "23", "name" => "Belize", "iso3" => "BLZ", "currency_code" => "BZD"],
            "BJ" => ["id" => "24", "name" => "Benin", "iso3" => "BEN", "currency_code" => "XOF"],
            "BM" => ["id" => "25", "name" => "Bermuda", "iso3" => "BMU", "currency_code" => "BMD"],
            "BT" => ["id" => "26", "name" => "Bhutan", "iso3" => "BTN", "currency_code" => "BTN"],
            "BO" => ["id" => "27", "name" => "Bolivia", "iso3" => "BOL", "currency_code" => "BOB"],
            "BQ" => ["id" => "28", "name" => "Bonaire, Sint Eustatius and Saba", "iso3" => "BES", "currency_code" => "USD"],
            "BA" => ["id" => "29", "name" => "Bosnia and Herzegovina", "iso3" => "BIH", "currency_code" => "BAM"],
            "BW" => ["id" => "30", "name" => "Botswana", "iso3" => "BWA", "currency_code" => "BWP"],
            "BV" => ["id" => "31", "name" => "Bouvet Island", "iso3" => "BVT", "currency_code" => "NOK"],
            "BR" => ["id" => "32", "name" => "Brazil", "iso3" => "BRA", "currency_code" => "BRL"],
            "IO" => ["id" => "33", "name" => "British Indian Ocean Territory", "iso3" => "IOT", "currency_code" => "USD"],
            "BN" => ["id" => "34", "name" => "Brunei Darussalam", "iso3" => "BRN", "currency_code" => "BND"],
            "BG" => ["id" => "35", "name" => "Bulgaria", "iso3" => "BGR", "currency_code" => "BGN"],
            "BF" => ["id" => "36", "name" => "Burkina Faso", "iso3" => "BFA", "currency_code" => "XOF"],
            "BI" => ["id" => "37", "name" => "Burundi", "iso3" => "BDI", "currency_code" => "BIF"],
            "KH" => ["id" => "38", "name" => "Cambodia", "iso3" => "KHM", "currency_code" => "KHR"],
            "CM" => ["id" => "39", "name" => "Cameroon", "iso3" => "CMR", "currency_code" => "XAF"],
            "CA" => ["id" => "40", "name" => "Canada", "iso3" => "CAN", "currency_code" => "CAD"],
            "CV" => ["id" => "41", "name" => "Cape Verde", "iso3" => "CPV", "currency_code" => "CVE"],
            "KY" => ["id" => "42", "name" => "Cayman Islands", "iso3" => "CYM", "currency_code" => "KYD"],
            "CF" => ["id" => "43", "name" => "Central African Republic", "iso3" => "CAF", "currency_code" => "XAF"],
            "TD" => ["id" => "44", "name" => "Chad", "iso3" => "TCD", "currency_code" => "XAF"],
            "CL" => ["id" => "45", "name" => "Chile", "iso3" => "CHL", "currency_code" => "CLP"],
            "CN" => ["id" => "46", "name" => "China", "iso3" => "CHN", "currency_code" => "CNY"],
            "CX" => ["id" => "47", "name" => "Christmas Island", "iso3" => "CXR", "currency_code" => "AUD"],
            "CC" => ["id" => "48", "name" => "Cocos (Keeling] Islands", "iso3" => "CCK", "currency_code" => "AUD"],
            "CO" => ["id" => "49", "name" => "Colombia", "iso3" => "COL", "currency_code" => "COP"],
            "KM" => ["id" => "50", "name" => "Comoros", "iso3" => "COM", "currency_code" => "KMF"],
            "CG" => ["id" => "51", "name" => "Congo", "iso3" => "COG", "currency_code" => "XAF"],
            "CD" => ["id" => "52", "name" => "Congo, Democratic Republic of the Congo", "iso3" => "COD", "currency_code" => "CDF"],
            "CK" => ["id" => "53", "name" => "Cook Islands", "iso3" => "COK", "currency_code" => "NZD"],
            "CR" => ["id" => "54", "name" => "Costa Rica", "iso3" => "CRI", "currency_code" => "CRC"],
            "CI" => ["id" => "55", "name" => "Cote D'Ivoire", "iso3" => "CIV", "currency_code" => "XOF"],
            "HR" => ["id" => "56", "name" => "Croatia", "iso3" => "HRV", "currency_code" => "HRK"],
            "CU" => ["id" => "57", "name" => "Cuba", "iso3" => "CUB", "currency_code" => "CUP"],
            "CW" => ["id" => "58", "name" => "Curacao", "iso3" => "CUW", "currency_code" => "ANG"],
            "CY" => ["id" => "59", "name" => "Cyprus", "iso3" => "CYP", "currency_code" => "EUR"],
            "CZ" => ["id" => "60", "name" => "Czech Republic", "iso3" => "CZE", "currency_code" => "CZK"],
            "DK" => ["id" => "61", "name" => "Denmark", "iso3" => "DNK", "currency_code" => "DKK"],
            "DJ" => ["id" => "62", "name" => "Djibouti", "iso3" => "DJI", "currency_code" => "DJF"],
            "DM" => ["id" => "63", "name" => "Dominica", "iso3" => "DMA", "currency_code" => "XCD"],
            "DO" => ["id" => "64", "name" => "Dominican Republic", "iso3" => "DOM", "currency_code" => "DOP"],
            "EC" => ["id" => "65", "name" => "Ecuador", "iso3" => "ECU", "currency_code" => "USD"],
            "EG" => ["id" => "66", "name" => "Egypt", "iso3" => "EGY", "currency_code" => "EGP"],
            "SV" => ["id" => "67", "name" => "El Salvador", "iso3" => "SLV", "currency_code" => "USD"],
            "GQ" => ["id" => "68", "name" => "Equatorial Guinea", "iso3" => "GNQ", "currency_code" => "XAF"],
            "ER" => ["id" => "69", "name" => "Eritrea", "iso3" => "ERI", "currency_code" => "ERN"],
            "EE" => ["id" => "70", "name" => "Estonia", "iso3" => "EST", "currency_code" => "EUR"],
            "ET" => ["id" => "71", "name" => "Ethiopia", "iso3" => "ETH", "currency_code" => "ETB"],
            "FK" => ["id" => "72", "name" => "Falkland Islands (Malvinas]", "iso3" => "FLK", "currency_code" => "FKP"],
            "FO" => ["id" => "73", "name" => "Faroe Islands", "iso3" => "FRO", "currency_code" => "DKK"],
            "FJ" => ["id" => "74", "name" => "Fiji", "iso3" => "FJI", "currency_code" => "FJD"],
            "FI" => ["id" => "75", "name" => "Finland", "iso3" => "FIN", "currency_code" => "EUR"],
            "FR" => ["id" => "76", "name" => "France", "iso3" => "FRA", "currency_code" => "EUR"],
            "GF" => ["id" => "77", "name" => "French Guiana", "iso3" => "GUF", "currency_code" => "EUR"],
            "PF" => ["id" => "78", "name" => "French Polynesia", "iso3" => "PYF", "currency_code" => "XPF"],
            "TF" => ["id" => "79", "name" => "French Southern Territories", "iso3" => "ATF", "currency_code" => "EUR"],
            "GA" => ["id" => "80", "name" => "Gabon", "iso3" => "GAB", "currency_code" => "XAF"],
            "GM" => ["id" => "81", "name" => "Gambia", "iso3" => "GMB", "currency_code" => "GMD"],
            "GE" => ["id" => "82", "name" => "Georgia", "iso3" => "GEO", "currency_code" => "GEL"],
            "DE" => ["id" => "83", "name" => "Germany", "iso3" => "DEU", "currency_code" => "EUR"],
            "GH" => ["id" => "84", "name" => "Ghana", "iso3" => "GHA", "currency_code" => "GHS"],
            "GI" => ["id" => "85", "name" => "Gibraltar", "iso3" => "GIB", "currency_code" => "GIP"],
            "GR" => ["id" => "86", "name" => "Greece", "iso3" => "GRC", "currency_code" => "EUR"],
            "GL" => ["id" => "87", "name" => "Greenland", "iso3" => "GRL", "currency_code" => "DKK"],
            "GD" => ["id" => "88", "name" => "Grenada", "iso3" => "GRD", "currency_code" => "XCD"],
            "GP" => ["id" => "89", "name" => "Guadeloupe", "iso3" => "GLP", "currency_code" => "EUR"],
            "GU" => ["id" => "90", "name" => "Guam", "iso3" => "GUM", "currency_code" => "USD"],
            "GT" => ["id" => "91", "name" => "Guatemala", "iso3" => "GTM", "currency_code" => "GTQ"],
            "GG" => ["id" => "92", "name" => "Guernsey", "iso3" => "GGY", "currency_code" => "GBP"],
            "GN" => ["id" => "93", "name" => "Guinea", "iso3" => "GIN", "currency_code" => "GNF"],
            "GW" => ["id" => "94", "name" => "Guinea-Bissau", "iso3" => "GNB", "currency_code" => "XOF"],
            "GY" => ["id" => "95", "name" => "Guyana", "iso3" => "GUY", "currency_code" => "GYD"],
            "HT" => ["id" => "96", "name" => "Haiti", "iso3" => "HTI", "currency_code" => "HTG"],
            "HM" => ["id" => "97", "name" => "Heard Island and Mcdonald Islands", "iso3" => "HMD", "currency_code" => "AUD"],
            "VA" => ["id" => "98", "name" => "Holy See (Vatican City State]", "iso3" => "VAT", "currency_code" => "EUR"],
            "HN" => ["id" => "99", "name" => "Honduras", "iso3" => "HND", "currency_code" => "HNL"],
            "HK" => ["id" => "100", "name" => "Hong Kong", "iso3" => "HKG", "currency_code" => "HKD"],
            "HU" => ["id" => "101", "name" => "Hungary", "iso3" => "HUN", "currency_code" => "HUF"],
            "IS" => ["id" => "102", "name" => "Iceland", "iso3" => "ISL", "currency_code" => "ISK"],
            "IN" => ["id" => "103", "name" => "India", "iso3" => "IND", "currency_code" => "INR"],
            "ID" => ["id" => "104", "name" => "Indonesia", "iso3" => "IDN", "currency_code" => "IDR"],
            "IR" => ["id" => "105", "name" => "Iran, Islamic Republic of", "iso3" => "IRN", "currency_code" => "IRR"],
            "IQ" => ["id" => "106", "name" => "Iraq", "iso3" => "IRQ", "currency_code" => "IQD"],
            "IE" => ["id" => "107", "name" => "Ireland", "iso3" => "IRL", "currency_code" => "EUR"],
            "IM" => ["id" => "108", "name" => "Isle of Man", "iso3" => "IMN", "currency_code" => "GBP"],
            "IL" => ["id" => "109", "name" => "Israel", "iso3" => "ISR", "currency_code" => "ILS"],
            "IT" => ["id" => "110", "name" => "Italy", "iso3" => "ITA", "currency_code" => "EUR"],
            "JM" => ["id" => "111", "name" => "Jamaica", "iso3" => "JAM", "currency_code" => "JMD"],
            "JP" => ["id" => "112", "name" => "Japan", "iso3" => "JPN", "currency_code" => "JPY"],
            "JE" => ["id" => "113", "name" => "Jersey", "iso3" => "JEY", "currency_code" => "GBP"],
            "JO" => ["id" => "114", "name" => "Jordan", "iso3" => "JOR", "currency_code" => "JOD"],
            "KZ" => ["id" => "115", "name" => "Kazakhstan", "iso3" => "KAZ", "currency_code" => "KZT"],
            "KE" => ["id" => "116", "name" => "Kenya", "iso3" => "KEN", "currency_code" => "KES"],
            "KI" => ["id" => "117", "name" => "Kiribati", "iso3" => "KIR", "currency_code" => "AUD"],
            "KP" => ["id" => "118", "name" => "Korea, Democratic People's Republic of", "iso3" => "PRK", "currency_code" => "KPW"],
            "KR" => ["id" => "119", "name" => "Korea, Republic of", "iso3" => "KOR", "currency_code" => "KRW"],
            "XK" => ["id" => "120", "name" => "Kosovo", "iso3" => "XKX", "currency_code" => "EUR"],
            "KW" => ["id" => "121", "name" => "Kuwait", "iso3" => "KWT", "currency_code" => "KWD"],
            "KG" => ["id" => "122", "name" => "Kyrgyzstan", "iso3" => "KGZ", "currency_code" => "KGS"],
            "LA" => ["id" => "123", "name" => "Lao People's Democratic Republic", "iso3" => "LAO", "currency_code" => "LAK"],
            "LV" => ["id" => "124", "name" => "Latvia", "iso3" => "LVA", "currency_code" => "EUR"],
            "LB" => ["id" => "125", "name" => "Lebanon", "iso3" => "LBN", "currency_code" => "LBP"],
            "LS" => ["id" => "126", "name" => "Lesotho", "iso3" => "LSO", "currency_code" => "LSL"],
            "LR" => ["id" => "127", "name" => "Liberia", "iso3" => "LBR", "currency_code" => "LRD"],
            "LY" => ["id" => "128", "name" => "Libyan Arab Jamahiriya", "iso3" => "LBY", "currency_code" => "LYD"],
            "LI" => ["id" => "129", "name" => "Liechtenstein", "iso3" => "LIE", "currency_code" => "CHF"],
            "LT" => ["id" => "130", "name" => "Lithuania", "iso3" => "LTU", "currency_code" => "EUR"],
            "LU" => ["id" => "131", "name" => "Luxembourg", "iso3" => "LUX", "currency_code" => "EUR"],
            "MO" => ["id" => "132", "name" => "Macao", "iso3" => "MAC", "currency_code" => "MOP"],
            "MK" => ["id" => "133", "name" => "Macedonia, the Former Yugoslav Republic of", "iso3" => "MKD", "currency_code" => "MKD"],
            "MG" => ["id" => "134", "name" => "Madagascar", "iso3" => "MDG", "currency_code" => "MGA"],
            "MW" => ["id" => "135", "name" => "Malawi", "iso3" => "MWI", "currency_code" => "MWK"],
            "MY" => ["id" => "136", "name" => "Malaysia", "iso3" => "MYS", "currency_code" => "MYR"],
            "MV" => ["id" => "137", "name" => "Maldives", "iso3" => "MDV", "currency_code" => "MVR"],
            "ML" => ["id" => "138", "name" => "Mali", "iso3" => "MLI", "currency_code" => "XOF"],
            "MT" => ["id" => "139", "name" => "Malta", "iso3" => "MLT", "currency_code" => "EUR"],
            "MH" => ["id" => "140", "name" => "Marshall Islands", "iso3" => "MHL", "currency_code" => "USD"],
            "MQ" => ["id" => "141", "name" => "Martinique", "iso3" => "MTQ", "currency_code" => "EUR"],
            "MR" => ["id" => "142", "name" => "Mauritania", "iso3" => "MRT", "currency_code" => "MRO"],
            "MU" => ["id" => "143", "name" => "Mauritius", "iso3" => "MUS", "currency_code" => "MUR"],
            "YT" => ["id" => "144", "name" => "Mayotte", "iso3" => "MYT", "currency_code" => "EUR"],
            "MX" => ["id" => "145", "name" => "Mexico", "iso3" => "MEX", "currency_code" => "MXN"],
            "FM" => ["id" => "146", "name" => "Micronesia, Federated States of", "iso3" => "FSM", "currency_code" => "USD"],
            "MD" => ["id" => "147", "name" => "Moldova, Republic of", "iso3" => "MDA", "currency_code" => "MDL"],
            "MC" => ["id" => "148", "name" => "Monaco", "iso3" => "MCO", "currency_code" => "EUR"],
            "MN" => ["id" => "149", "name" => "Mongolia", "iso3" => "MNG", "currency_code" => "MNT"],
            "ME" => ["id" => "150", "name" => "Montenegro", "iso3" => "MNE", "currency_code" => "EUR"],
            "MS" => ["id" => "151", "name" => "Montserrat", "iso3" => "MSR", "currency_code" => "XCD"],
            "MA" => ["id" => "152", "name" => "Morocco", "iso3" => "MAR", "currency_code" => "MAD"],
            "MZ" => ["id" => "153", "name" => "Mozambique", "iso3" => "MOZ", "currency_code" => "MZN"],
            "MM" => ["id" => "154", "name" => "Myanmar", "iso3" => "MMR", "currency_code" => "MMK"],
            "NA" => ["id" => "155", "name" => "Namibia", "iso3" => "NAM", "currency_code" => "NAD"],
            "NR" => ["id" => "156", "name" => "Nauru", "iso3" => "NRU", "currency_code" => "AUD"],
            "NP" => ["id" => "157", "name" => "Nepal", "iso3" => "NPL", "currency_code" => "NPR"],
            "NL" => ["id" => "158", "name" => "Netherlands", "iso3" => "NLD", "currency_code" => "EUR"],
            "AN" => ["id" => "159", "name" => "Netherlands Antilles", "iso3" => "ANT", "currency_code" => "ANG"],
            "NC" => ["id" => "160", "name" => "New Caledonia", "iso3" => "NCL", "currency_code" => "XPF"],
            "NZ" => ["id" => "161", "name" => "New Zealand", "iso3" => "NZL", "currency_code" => "NZD"],
            "NI" => ["id" => "162", "name" => "Nicaragua", "iso3" => "NIC", "currency_code" => "NIO"],
            "NE" => ["id" => "163", "name" => "Niger", "iso3" => "NER", "currency_code" => "XOF"],
            "NG" => ["id" => "164", "name" => "Nigeria", "iso3" => "NGA", "currency_code" => "NGN"],
            "NU" => ["id" => "165", "name" => "Niue", "iso3" => "NIU", "currency_code" => "NZD"],
            "NF" => ["id" => "166", "name" => "Norfolk Island", "iso3" => "NFK", "currency_code" => "AUD"],
            "MP" => ["id" => "167", "name" => "Northern Mariana Islands", "iso3" => "MNP", "currency_code" => "USD"],
            "NO" => ["id" => "168", "name" => "Norway", "iso3" => "NOR", "currency_code" => "NOK"],
            "OM" => ["id" => "169", "name" => "Oman", "iso3" => "OMN", "currency_code" => "OMR"],
            "PK" => ["id" => "170", "name" => "Pakistan", "iso3" => "PAK", "currency_code" => "PKR"],
            "PW" => ["id" => "171", "name" => "Palau", "iso3" => "PLW", "currency_code" => "USD"],
            "PS" => ["id" => "172", "name" => "Palestinian Territory, Occupied", "iso3" => "PSE", "currency_code" => "ILS"],
            "PA" => ["id" => "173", "name" => "Panama", "iso3" => "PAN", "currency_code" => "PAB"],
            "PG" => ["id" => "174", "name" => "Papua New Guinea", "iso3" => "PNG", "currency_code" => "PGK"],
            "PY" => ["id" => "175", "name" => "Paraguay", "iso3" => "PRY", "currency_code" => "PYG"],
            "PE" => ["id" => "176", "name" => "Peru", "iso3" => "PER", "currency_code" => "PEN"],
            "PH" => ["id" => "177", "name" => "Philippines", "iso3" => "PHL", "currency_code" => "PHP"],
            "PN" => ["id" => "178", "name" => "Pitcairn", "iso3" => "PCN", "currency_code" => "NZD"],
            "PL" => ["id" => "179", "name" => "Poland", "iso3" => "POL", "currency_code" => "PLN"],
            "PT" => ["id" => "180", "name" => "Portugal", "iso3" => "PRT", "currency_code" => "EUR"],
            "PR" => ["id" => "181", "name" => "Puerto Rico", "iso3" => "PRI", "currency_code" => "USD"],
            "QA" => ["id" => "182", "name" => "Qatar", "iso3" => "QAT", "currency_code" => "QAR"],
            "RE" => ["id" => "183", "name" => "Reunion", "iso3" => "REU", "currency_code" => "EUR"],
            "RO" => ["id" => "184", "name" => "Romania", "iso3" => "ROM", "currency_code" => "RON"],
            "RU" => ["id" => "185", "name" => "Russian Federation", "iso3" => "RUS", "currency_code" => "RUB"],
            "RW" => ["id" => "186", "name" => "Rwanda", "iso3" => "RWA", "currency_code" => "RWF"],
            "BL" => ["id" => "187", "name" => "Saint Barthelemy", "iso3" => "BLM", "currency_code" => "EUR"],
            "SH" => ["id" => "188", "name" => "Saint Helena", "iso3" => "SHN", "currency_code" => "SHP"],
            "KN" => ["id" => "189", "name" => "Saint Kitts and Nevis", "iso3" => "KNA", "currency_code" => "XCD"],
            "LC" => ["id" => "190", "name" => "Saint Lucia", "iso3" => "LCA", "currency_code" => "XCD"],
            "MF" => ["id" => "191", "name" => "Saint Martin", "iso3" => "MAF", "currency_code" => "EUR"],
            "PM" => ["id" => "192", "name" => "Saint Pierre and Miquelon", "iso3" => "SPM", "currency_code" => "EUR"],
            "VC" => ["id" => "193", "name" => "Saint Vincent and the Grenadines", "iso3" => "VCT", "currency_code" => "XCD"],
            "WS" => ["id" => "194", "name" => "Samoa", "iso3" => "WSM", "currency_code" => "WST"],
            "SM" => ["id" => "195", "name" => "San Marino", "iso3" => "SMR", "currency_code" => "EUR"],
            "ST" => ["id" => "196", "name" => "Sao Tome and Principe", "iso3" => "STP", "currency_code" => "STD"],
            "SA" => ["id" => "197", "name" => "Saudi Arabia", "iso3" => "SAU", "currency_code" => "SAR"],
            "SN" => ["id" => "198", "name" => "Senegal", "iso3" => "SEN", "currency_code" => "XOF"],
            "RS" => ["id" => "199", "name" => "Serbia", "iso3" => "SRB", "currency_code" => "RSD"],
            "CS" => ["id" => "200", "name" => "Serbia and Montenegro", "iso3" => "SCG", "currency_code" => "RSD"],
            "SC" => ["id" => "201", "name" => "Seychelles", "iso3" => "SYC", "currency_code" => "SCR"],
            "SL" => ["id" => "202", "name" => "Sierra Leone", "iso3" => "SLE", "currency_code" => "SLL"],
            "SG" => ["id" => "203", "name" => "Singapore", "iso3" => "SGP", "currency_code" => "SGD"],
            "SX" => ["id" => "204", "name" => "Sint Maarten", "iso3" => "SXM", "currency_code" => "ANG"],
            "SK" => ["id" => "205", "name" => "Slovakia", "iso3" => "SVK", "currency_code" => "EUR"],
            "SI" => ["id" => "206", "name" => "Slovenia", "iso3" => "SVN", "currency_code" => "EUR"],
            "SB" => ["id" => "207", "name" => "Solomon Islands", "iso3" => "SLB", "currency_code" => "SBD"],
            "SO" => ["id" => "208", "name" => "Somalia", "iso3" => "SOM", "currency_code" => "SOS"],
            "ZA" => ["id" => "209", "name" => "South Africa", "iso3" => "ZAF", "currency_code" => "ZAR"],
            "GS" => ["id" => "210", "name" => "South Georgia and the South Sandwich Islands", "iso3" => "SGS", "currency_code" => "GBP"],
            "SS" => ["id" => "211", "name" => "South Sudan", "iso3" => "SSD", "currency_code" => "SSP"],
            "ES" => ["id" => "212", "name" => "Spain", "iso3" => "ESP", "currency_code" => "EUR"],
            "LK" => ["id" => "213", "name" => "Sri Lanka", "iso3" => "LKA", "currency_code" => "LKR"],
            "SD" => ["id" => "214", "name" => "Sudan", "iso3" => "SDN", "currency_code" => "SDG"],
            "SR" => ["id" => "215", "name" => "Suriname", "iso3" => "SUR", "currency_code" => "SRD"],
            "SJ" => ["id" => "216", "name" => "Svalbard and Jan Mayen", "iso3" => "SJM", "currency_code" => "NOK"],
            "SZ" => ["id" => "217", "name" => "Swaziland", "iso3" => "SWZ", "currency_code" => "SZL"],
            "SE" => ["id" => "218", "name" => "Sweden", "iso3" => "SWE", "currency_code" => "SEK"],
            "CH" => ["id" => "219", "name" => "Switzerland", "iso3" => "CHE", "currency_code" => "CHF"],
            "SY" => ["id" => "220", "name" => "Syrian Arab Republic", "iso3" => "SYR", "currency_code" => "SYP"],
            "TW" => ["id" => "221", "name" => "Taiwan, Province of China", "iso3" => "TWN", "currency_code" => "TWD"],
            "TJ" => ["id" => "222", "name" => "Tajikistan", "iso3" => "TJK", "currency_code" => "TJS"],
            "TZ" => ["id" => "223", "name" => "Tanzania, United Republic of", "iso3" => "TZA", "currency_code" => "TZS"],
            "TH" => ["id" => "224", "name" => "Thailand", "iso3" => "THA", "currency_code" => "THB"],
            "TL" => ["id" => "225", "name" => "Timor-Leste", "iso3" => "TLS", "currency_code" => "USD"],
            "TG" => ["id" => "226", "name" => "Togo", "iso3" => "TGO", "currency_code" => "XOF"],
            "TK" => ["id" => "227", "name" => "Tokelau", "iso3" => "TKL", "currency_code" => "NZD"],
            "TO" => ["id" => "228", "name" => "Tonga", "iso3" => "TON", "currency_code" => "TOP"],
            "TT" => ["id" => "229", "name" => "Trinidad and Tobago", "iso3" => "TTO", "currency_code" => "TTD"],
            "TN" => ["id" => "230", "name" => "Tunisia", "iso3" => "TUN", "currency_code" => "TND"],
            "TR" => ["id" => "231", "name" => "Turkey", "iso3" => "TUR", "currency_code" => "TRY"],
            "TM" => ["id" => "232", "name" => "Turkmenistan", "iso3" => "TKM", "currency_code" => "TMT"],
            "TC" => ["id" => "233", "name" => "Turks and Caicos Islands", "iso3" => "TCA", "currency_code" => "USD"],
            "TV" => ["id" => "234", "name" => "Tuvalu", "iso3" => "TUV", "currency_code" => "AUD"],
            "UG" => ["id" => "235", "name" => "Uganda", "iso3" => "UGA", "currency_code" => "UGX"],
            "UA" => ["id" => "236", "name" => "Ukraine", "iso3" => "UKR", "currency_code" => "UAH"],
            "AE" => ["id" => "237", "name" => "United Arab Emirates", "iso3" => "ARE", "currency_code" => "AED"],
            "GB" => ["id" => "238", "name" => "United Kingdom", "iso3" => "GBR", "currency_code" => "GBP"],
            "US" => ["id" => "239", "name" => "United States", "iso3" => "USA", "currency_code" => "USD"],
            "UM" => ["id" => "240", "name" => "United States Minor Outlying Islands", "iso3" => "UMI", "currency_code" => "USD"],
            "UY" => ["id" => "241", "name" => "Uruguay", "iso3" => "URY", "currency_code" => "UYU"],
            "UZ" => ["id" => "242", "name" => "Uzbekistan", "iso3" => "UZB", "currency_code" => "UZS"],
            "VU" => ["id" => "243", "name" => "Vanuatu", "iso3" => "VUT", "currency_code" => "VUV"],
            "VE" => ["id" => "244", "name" => "Venezuela", "iso3" => "VEN", "currency_code" => "VEF"],
            "VN" => ["id" => "245", "name" => "Viet Nam", "iso3" => "VNM", "currency_code" => "VND"],
            "VG" => ["id" => "246", "name" => "Virgin Islands, British", "iso3" => "VGB", "currency_code" => "USD"],
            "VI" => ["id" => "247", "name" => "Virgin Islands, U.s.", "iso3" => "VIR", "currency_code" => "USD"],
            "WF" => ["id" => "248", "name" => "Wallis and Futuna", "iso3" => "WLF", "currency_code" => "XPF"],
            "EH" => ["id" => "249", "name" => "Western Sahara", "iso3" => "ESH", "currency_code" => "MAD"],
            "YE" => ["id" => "250", "name" => "Yemen", "iso3" => "YEM", "currency_code" => "YER"],
            "ZM" => ["id" => "251", "name" => "Zambia", "iso3" => "ZMB", "currency_code" => "ZMW"],
            "ZW" => ["id" => "252", "name" => "Zimbabwe", "iso3" => "ZWE", "currency_code" => "ZWL"]
        ];

        foreach($countries as $key => $country) {
            Country::create([
                'name' => $country['name'],
                'iso' => $key,
                'iso3' => $country['iso3'],
                'currency_code' => $country['currency_code'],
            ]);
        }
    }
}
