<x-app-layout>
<div class="container my-5">
    <h1>Datenschutz</h1>
    <br>
    <p>Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder eMail-Adressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben. Diese Website benutzt Google Analytics und Google Remarketing. Die Dienste werden von Google Inc. („Google“) angeboten. Sie können darüber hinaus die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link (http://tools.google.com/dlpage/gaoptout?hl=de) verfügbare Browser-Plugin herunterladen und installieren.

        Google Analytics und Google Remarketing sind Dienstleistungen von Google. Von Google werden sog. „Cookies“, Textdateien, verwendet, die auf Ihrem Computer gespeichert werden. Hierdurch wird die Nutzungsanalyse dieser Website durch Sie ermöglicht. Durch den Cookie werden Informationen über Ihre Benutzung dieser Website erzeugt und diese (einschließlich Ihrer IP-Adresse) an einen Server von Google in den USA übertragen und gespeichert. Die Nutzung der Funktion „anonymizeIP“ für Ihre IP-Adresse garantiert innerhalb der Europäischen Union oder Mitgliedsstaaten des europäischen Wirtschaftsraums die Kürzung der IP-Adresse um das letzte Oktett, wodurch eine eindeutige Zuordnung der IP-Adresse somit nicht mehr möglich ist. Google beachtet die Datenschutzbestimmungen des „US-Safe-Harbor“-Abkommens und ist beim „Safe Harbor“-Programm des US-Handelsministeriums registriert. Die Informationen werden von Google genutzt, um Ihre Nutzung der Website auszuwerten. Es werden Reports über die Websiteaktivitäten für den Websitebetreiber erstellt und weitere im Zusammenhang mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen ermöglicht. Die Informationen werden ggf. von Google an Dritte übertragen, sofern dies gesetzlich vorgeschrieben wird oder Dritte diese Daten im Auftrag von Google verarbeiten. Es werden Anzeigen auf Websites im Internet durch Drittanbieter und Google geschaltet. Google und Drittanbieter werden die Daten nutzen, um Werbung auf Webseiten Dritter zu schalten. Ihre IP-Adresse wird in keinem Fall mit anderen Daten von Google in Verbindung gebracht. Der Datenerhebung und -speicherung kann jederzeit mit Wirkung für die Zukunft widersprochen werden.

        ​Sie können die Verwendung und Speicherung von Cookies durch Google durch eine entsprechende Einstellung Ihrer Browser-Software deaktivieren, indem Sie die Seite www.google.de/privacy/ads aufrufen und den „Opt-Out“ Button betätigen. Alternativ können Sie die Verwendung von Cookies durch Drittanbieter deaktivieren, indem sie die Deaktivierungsseite der Netzwerkwerbeinitiative unter www.networkadvertising.org/managing/opt_out.asp aufrufen. Weitere Hinweise zu den Bestimmungen von Google finden Sie unter www.google.com/intl/de/privacy. Sollten Sie der Verwendung von Cookies widersprechen, weisen wir Sie darauf hin, dass Sie ggf. nicht alle Funktionen dieser Webseite vollumfänglich nutzen können.
        <br> <br>
        (Auszug Datenschutzrichtlinien Google Analytics)
        http://www.google.com/analytics/terms/de.html</p>

</div>
</x-app-layout>
